services:
  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    environment:
      MEILI_ENV: "development"
      MEILI_MASTER_KEY: "${MASTER_KEY}"
      MEILI_NO_ANALYTICS: "true"
      MEILI_LOG_LEVEL: "INFO"
    volumes:
      - ./meili_data:/meili_data